language: node_js
node_js:
  - node
os:
  - linux
dist: xenial
deploy:
  edge: true
  provider: firebase
  token:
    secure: GuAAUOsIXM6aRQc9xZlia0FJ3rvliiAsiw18Zj3sJ6yqlsyyyy1LMZHbgWyCrWFbHbCreRAMAbHCk3d2kEQ0XMpLZt8HYK5RnDdgDnCu2hiu0ANElpOiDqsmE0whlWbdbkNquTVDzm3IcTh5e2BaG2vo5ztT79gJy12U9kxnizo3fUnRM9bNaUCH3S0uTRui5ztMmkqmtX0W9DLcMiOStsd2kB9N23LDez/Lc1rh4gZRSEqBkEXHtVxENpKovnaoRc9IYaGjEw99wQPYR8r/u2hPUhKig0Mpavtt/HRJX/Ea5KLi5jhwezNs79JUNmZJJV/sF5Yq3XTyAkanG2AqgOp4jc9wcXkzopla5ZFvbnboThp9BXXtkRR+BJc41wmRfTDTFSZBNOQgrve10bi7GOycixHMQauOx9HGBkqW4t38UTKV3GVQ4oHmF+j94S6TPh5eDqjJpUhENl1OkEVuzX3YffJuOWd9uJQ0fqTEHMpTS7N+LKLTyB/oSoas6w1705QkBA7ZAE9z4WxOybyh2I1pLpb6PABmvl0Y+GWuJJ03zfWOMNAB7zGGDmOwPMXWXXkfZNbzblx1maZjdH4e35/+mNJMEFe3CA5fcX1CX9m33hrs1eU0ZSKHf4e2ve5fT6yL2aXMO4yR1m0fcqxcT5HkSK7E425fUzDEnWGMAok=
env:
  - secure: 'LXJ57LlooIVlkc2fFFK75uClBnH0VN+21riSZgKbe6ltottrhR+BginSbPeJbO2rjeZ7r21jN3KvMGWetxFhbGBPgcAfNK4VZSE5ilnDqLPcYj3Dp2ftcnHgfX58PM8PI7YNXUDydEv8vubg+1lt7nfoV3W2Pms6DXtQIcPtX3IDzpP8zPgM2uYnzgd0e7qwsIQ/TzzliqNq/7IRx9Qr66EKfUdh+/GkfhByq+gVUtSuJq/L01HdhDjHgmY8j1y1Lu5V1XwUNCUuuGVkIu5Rnk42mxS1+xZO9u+qOOyJyoZsBTlpiHbIIXH3ZXyFf8wLQ4cQhfwD+2Ep6wybj4wB0baes2KQyr2nGTaRgOPhjEr3+e51YOMED1D++mv6wmgMVn6qrfAEPTjRm4D8XTKcDAzKFtC5CfWmelMpDwfvTCs/uaeOdn64iw1HkJxf6+n9WBppxXhiJG0XSaQrQg1H7tPPHL5W6INFxRPDc9a81F+EL6V7Hi7oil7BYF2mOcQF98B7Pip5Os3gAwVHGRt6T8uyAzi0FWCwtlQS8DnI8hfXfux1OxvrL00TQ/NDan3VvKLTk4Op9GqIH/p/BbXTalXzp+mM4bmgsd5Ug2KV8tP6xBGqBHB+7fB4cxj68YZMxrAGGxBio8m/wpfGfUxlnhJ1Vxsq4RBzLaT8qOTTMB8='
