language: node_js
node_js:
  - 12
os: linux
dist: xenial
deploy:
  provider: firebase
  token:
    secure: GuAAUOsIXM6aRQc9xZlia0FJ3rvliiAsiw18Zj3sJ6yqlsyyyy1LMZHbgWyCrWFbHbCreRAMAbHCk3d2kEQ0XMpLZt8HYK5RnDdgDnCu2hiu0ANElpOiDqsmE0whlWbdbkNquTVDzm3IcTh5e2BaG2vo5ztT79gJy12U9kxnizo3fUnRM9bNaUCH3S0uTRui5ztMmkqmtX0W9DLcMiOStsd2kB9N23LDez/Lc1rh4gZRSEqBkEXHtVxENpKovnaoRc9IYaGjEw99wQPYR8r/u2hPUhKig0Mpavtt/HRJX/Ea5KLi5jhwezNs79JUNmZJJV/sF5Yq3XTyAkanG2AqgOp4jc9wcXkzopla5ZFvbnboThp9BXXtkRR+BJc41wmRfTDTFSZBNOQgrve10bi7GOycixHMQauOx9HGBkqW4t38UTKV3GVQ4oHmF+j94S6TPh5eDqjJpUhENl1OkEVuzX3YffJuOWd9uJQ0fqTEHMpTS7N+LKLTyB/oSoas6w1705QkBA7ZAE9z4WxOybyh2I1pLpb6PABmvl0Y+GWuJJ03zfWOMNAB7zGGDmOwPMXWXXkfZNbzblx1maZjdH4e35/+mNJMEFe3CA5fcX1CX9m33hrs1eU0ZSKHf4e2ve5fT6yL2aXMO4yR1m0fcqxcT5HkSK7E425fUzDEnWGMAok=
