language: node_js
node_js:
- 12
before_deploy:
- npm run build
deploy:
  provider: firebase
env:
  global:
    secure: oK/13G2gsbgv4+n3ZljukWtjvW1JuxZk8ZVxFSyBlPl7UG/fQzP9Kf4E9RNfI9pd0fB23JcM9MwbH4vCWvEPbB6Uzo1lyq4fCaHmsdkrdyZhqPG6efvXcspuhlisLzRD/IIFrqpyNNVxN4MaR0u7Ett7K2e3bnYFC9BBVidbuPLIEO/ucKt/3HjweRPZ+gtziFnBBy3SayKsStCQSM7PLOwS5FSU5WCsWHCGkQbPxPBVJzITtX4LAUYCROESJNsxaobGdCrm8VEtaHwKYjr0X8aWWXHTITt3GCio1EOnEjmJXnn1kI+4GYsNPC1FyuSukgTAQrUeY7Zl+lzLWUmlhWfXECRxLdwpijfjWGeLX2xwLl1K8plqeZVB6BR0e3CIo38kuhBF+TNuTwoYo3j83+aHUth2eJiqrTqDV41o8UKcVk6yimmsxlM1K6SwHKuf63ZHHNO7LlXoS9mgZQXOJzDMMKsj2gtu58bS4PMhZGmtm87R35mAavAQj+sX9cuJjuhULwAvRtS6ia9T27YNf57oLz//Hc5FFmQRL+ylTS6Q7fWAQFQina1cvkekjUoeS5Ye5YyRN2FCabPMlkJrT3vfd++US7c6UarGNClJW1E0Nt0tIZQvdi78NcnHuH70Ovp09WfelYTEbDmWgo55qwiFGXtEVdz8jr0xXIXmiow=
